spring:
   datasource:
      username: root
      password: 876123as
      url: jdbc:mysql://localhost:3306/apl
      driver-class-name: com.mysql.jdbc.Driver
   jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
   mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

